# URL limpia apuntando al pooler de Irlanda con SSL obligatorio y corrector de Prepared Statements
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# Tu usuario completo del pooler
spring.datasource.username=postgres.mhxwsnyjmahyicouoqem

# Tu contraseña activa
spring.datasource.password=ShinoviSambrailo

# Configuración para que Spring entienda el dialecto de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true